# Generated by Django 5.2.12 on 2026-03-17 04:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professionals", "0002_unique_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professional",
            name="contact",
            field=models.CharField(
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="O contato deve estar em um formato válido (ex: 11999998888).",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
    ]
