# Generated by Django 5.2.12 on 2026-03-17 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("professionals", "0003_alter_professional_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="professional",
            options={
                "ordering": ["social_name"],
                "verbose_name": "Profissional",
                "verbose_name_plural": "Profissionais",
            },
        ),
        migrations.AlterField(
            model_name="professional",
            name="contact",
            field=models.CharField(
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="""O contato deve estar em um formato válido.
                        Ex: (11) 91234-5678""",
                        regex="^\\+?[\\d\\s\\(\\)-]{8,20}$",
                    )
                ],
            ),
        ),
    ]
