# Generated by Django 5.2.12 on 2026-03-17 14:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={
                "ordering": ["date"],
                "verbose_name": "Consulta",
                "verbose_name_plural": "Consultas",
            },
        ),
    ]
